spring.application.name=api-crud-biblioteca

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/biblioteca
spring.data.mongodb.auto-index-creation=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Cache
spring.cache.type=redis

# SpringDoc
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
